name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ME_Velu_NodeGoat
          cx_tenant: ama-partners
          base_uri: https://ind.iam.checkmarx.net/ 
          cx_client_id: ME123_CxOne_Client
          cx_client_secret: BQHNkrH9QleEGjTuwdAv8hoJNrFFO6Pm
          additional_params: --report-format sarif --output-path cx_result.sarif
      - name: List directory contents
        run: ls -l
      - name: List directory contents of the current directory
        run: ls -l ${{ github.workspace }}
      - name: Set permissions for SARIF file
        run: chmod 644 cx_result.sarif    
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: cx_result.sarif
